/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminPanelProtectedRouteRouteImport } from './routes/admin/panel/_protected/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminPanelProtectedIndexRouteImport } from './routes/admin/panel/_protected/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelProtectedRouteRoute =
  AdminPanelProtectedRouteRouteImport.update({
    id: '/admin/panel/_protected',
    path: '/admin/panel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelProtectedIndexRoute =
  AdminPanelProtectedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminPanelProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/panel': typeof AdminPanelProtectedRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/panel/': typeof AdminPanelProtectedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/panel': typeof AdminPanelProtectedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/panel/_protected': typeof AdminPanelProtectedRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/panel/_protected/': typeof AdminPanelProtectedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/login'
    | '/admin/panel'
    | '/api/auth/$'
    | '/admin/panel/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/admin/login' | '/api/auth/$' | '/admin/panel'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/login'
    | '/admin/panel/_protected'
    | '/api/auth/$'
    | '/admin/panel/_protected/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPanelProtectedRouteRoute: typeof AdminPanelProtectedRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/panel/_protected': {
      id: '/admin/panel/_protected'
      path: '/admin/panel'
      fullPath: '/admin/panel'
      preLoaderRoute: typeof AdminPanelProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/panel/_protected/': {
      id: '/admin/panel/_protected/'
      path: '/'
      fullPath: '/admin/panel/'
      preLoaderRoute: typeof AdminPanelProtectedIndexRouteImport
      parentRoute: typeof AdminPanelProtectedRouteRoute
    }
  }
}

interface AdminPanelProtectedRouteRouteChildren {
  AdminPanelProtectedIndexRoute: typeof AdminPanelProtectedIndexRoute
}

const AdminPanelProtectedRouteRouteChildren: AdminPanelProtectedRouteRouteChildren =
  {
    AdminPanelProtectedIndexRoute: AdminPanelProtectedIndexRoute,
  }

const AdminPanelProtectedRouteRouteWithChildren =
  AdminPanelProtectedRouteRoute._addFileChildren(
    AdminPanelProtectedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPanelProtectedRouteRoute: AdminPanelProtectedRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
