/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResendVerificationRouteImport } from './routes/resend-verification'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminPanelProtectedRouteRouteImport } from './routes/admin/panel/_protected/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminPanelProtectedIndexRouteImport } from './routes/admin/panel/_protected/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResendVerificationRoute = ResendVerificationRouteImport.update({
  id: '/resend-verification',
  path: '/resend-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelProtectedRouteRoute =
  AdminPanelProtectedRouteRouteImport.update({
    id: '/admin/panel/_protected',
    path: '/admin/panel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelProtectedIndexRoute =
  AdminPanelProtectedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminPanelProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/resend-verification': typeof ResendVerificationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/panel': typeof AdminPanelProtectedRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/panel/': typeof AdminPanelProtectedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/resend-verification': typeof ResendVerificationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/panel': typeof AdminPanelProtectedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/resend-verification': typeof ResendVerificationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/panel/_protected': typeof AdminPanelProtectedRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/panel/_protected/': typeof AdminPanelProtectedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/resend-verification'
    | '/reset-password'
    | '/verify-email'
    | '/admin/login'
    | '/admin/panel'
    | '/api/auth/$'
    | '/admin/panel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/resend-verification'
    | '/reset-password'
    | '/verify-email'
    | '/admin/login'
    | '/api/auth/$'
    | '/admin/panel'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/resend-verification'
    | '/reset-password'
    | '/verify-email'
    | '/admin/login'
    | '/admin/panel/_protected'
    | '/api/auth/$'
    | '/admin/panel/_protected/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResendVerificationRoute: typeof ResendVerificationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPanelProtectedRouteRoute: typeof AdminPanelProtectedRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resend-verification': {
      id: '/resend-verification'
      path: '/resend-verification'
      fullPath: '/resend-verification'
      preLoaderRoute: typeof ResendVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/panel/_protected': {
      id: '/admin/panel/_protected'
      path: '/admin/panel'
      fullPath: '/admin/panel'
      preLoaderRoute: typeof AdminPanelProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/panel/_protected/': {
      id: '/admin/panel/_protected/'
      path: '/'
      fullPath: '/admin/panel/'
      preLoaderRoute: typeof AdminPanelProtectedIndexRouteImport
      parentRoute: typeof AdminPanelProtectedRouteRoute
    }
  }
}

interface AdminPanelProtectedRouteRouteChildren {
  AdminPanelProtectedIndexRoute: typeof AdminPanelProtectedIndexRoute
}

const AdminPanelProtectedRouteRouteChildren: AdminPanelProtectedRouteRouteChildren =
  {
    AdminPanelProtectedIndexRoute: AdminPanelProtectedIndexRoute,
  }

const AdminPanelProtectedRouteRouteWithChildren =
  AdminPanelProtectedRouteRoute._addFileChildren(
    AdminPanelProtectedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResendVerificationRoute: ResendVerificationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPanelProtectedRouteRoute: AdminPanelProtectedRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
